Repository amichai-bd/riscv-multi-core-lotr, pull requests merged in 2021-06, with the labels that each got.

#71 adding codeowners file
  doc/CODEOWNERS
Labels: Other-Project-Task

#82 Fix path in source/lotr/ .f file
  source/lotr/lotr_list.f
Labels: enhancement

#89 Rc update
  doc/RC_doc/MAS_RC.docx
  source/rc/rtl/lotr_defines.sv
  source/rc/rtl/mro.sv
  source/rc/rtl/rc.sv
  source/rc/rtl/rc_tb.sv
Labels: documentation, enhancement
